{% set python_min = '3.11' %}
{% set name = "ecodata" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jemissik/ecodata/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 747c28102b139a35b91ffd2bb182cee615ca2f0a88d4a35bc13890611de98903

build:
  noarch: python
  script: {{ PREFIX }}/bin/python -m pip install . -vv
  number: 1

outputs:
  - name: ecodata
    build:
      noarch: python
      script: {{ PREFIX }}/bin/python -m pip install .
    requirements:
      host:
        - python {{ python_min }}
        - pip
      run:
        - python >={{ python_min }}
        - cartopy
        - geopandas
        - matplotlib
        - pandas
        - shapely <2.0
        - xarray
        - dask 
        - netCDF4
        - bottleneck
        - cfgrib
        - rasterio
        - numpy <1.24
        - rioxarray
        - hvplot
        - bokeh <3.4
        - panel >=1,<1.4
        - datashader
        - geoviews >=1.10
        - geocube
        - ffmpeg
        - gdown <4.6

    test:
      requires:
        - python {{ python_min }}
      imports:
        - ecodata

    about:
      summary: |
        Tools to access and process remote sensing and other environmental
        data products and prepare them for further use along with animal movement data
      home: https://github.com/jemissik/ecodata
      license: MIT
      license_file: LICENSE
      doc_url: https://ecodata-apps.readthedocs.io
      dev_url: https://github.com/jemissik/ecodata

  - name: ecodata-menu
    build:
      noarch: python
      script:
        - mkdir -p "${PREFIX}/Menu"
        - sed "s/__PKG_VERSION__/{{ PKG_VERSION }}/" "{{ SRC_DIR }}/resources/conda_menu_config.json" > "{{ PREFIX }}/Menu/ecodata-menu.json"
    requirements:
      build:
        - sed  # [unix]
      run:
        - ecodata {{ version }}.*
    test:
      requires:
        - python {{ python_min }}
      imports:
        - ecodata
      commands:
        - test -f ${CONDA_PREFIX}/Menu/ecodata-menu.json
    about:
      home: https://github.com/jemissik/ecodata
      license: MIT
      license_file: LICENSE
      doc_url: https://ecodata-apps.readthedocs.io
      dev_url: https://github.com/jemissik/ecodata
      summary: provides menu icons for ecodata
      description: provides menu icons for ecodata

about:
  summary: |
    Tools to access and process remote sensing and other environmental
    data products and prepare them for further use along with animal movement data
  home: https://github.com/jemissik/ecodata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jemissik
    - madeline-scyphers
