{% set name = "ecodata" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jemissik/ecodata/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3bbe402bf2c914ef61d8795cd99886ab48a7a340fc058f6824036ae2c077054c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >3.8
    - pip
  run:
    - python >3.8
    - cartopy
    - geopandas
    - matplotlib
    - pandas
    - shapely <2.0
    - xarray
    - dask ==2023.4.0
    - netCDF4
    - bottleneck
    - cfgrib
    - rasterio
    - numpy <1.24
    - rioxarray
    - hvplot
    - panel >=1,<1.4
    - datashader
    - geoviews >=1.10
    - geocube
    - ffmpeg
    - gdown <4.6

test:
  imports:
    - ecodata

about:
  summary: |
    Tools to access and process remote sensing and other environmental
    data products and prepare them for further use along with animal movement data
  home: https://github.com/jemissik/ecodata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jemissik
    - madeline-scyphers
