{% set name = "ecodata" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jemissik/ecodata/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 095ea878297e7275773cf5ba9be969ccb9ec015be846edf2c13aef6a77ca6153

build:
  noarch: python
  script: {{ PREFIX }}/bin/python -m pip install . -vv
  number: 0

outputs:
  - name: ecodata
    build:
      noarch: python
      script: {{ PREFIX }}/bin/python -m pip install .
    requirements:
      host:
        - python >3.8
        - pip
      run:
        - python >3.8
        - cartopy
        - geopandas
        - matplotlib
        - pandas
        - shapely <2.0
        - xarray
        - dask ==2023.4.0
        - netCDF4
        - bottleneck
        - cfgrib
        - rasterio
        - numpy <1.24
        - rioxarray
        - hvplot
        - bokeh <3.4
        - panel >=1,<1.4
        - datashader
        - geoviews >=1.10
        - geocube
        - ffmpeg
        - gdown <4.6

    test:
      imports:
        - ecodata

about:
  summary: |
    Tools to access and process remote sensing and other environmental
    data products and prepare them for further use along with animal movement data
  home: https://github.com/jemissik/ecodata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jemissik
    - madeline-scyphers
