{% set name = "ecodata" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jemissik/ecodata/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e6c07a1338a206ad95e49315fe139aeb2c55652c41b4f4ef4c5e33754a322b89

build:
  noarch: python
  script: {{ PREFIX }}/bin/python -m pip install . -vv
  number: 1

outputs:
  - name: ecodata
    build:
      noarch: python
      script: {{ PREFIX }}/bin/python -m pip install .
    requirements:
      host:
        - python >3.11
        - pip
        - setuptools
        - wheel
      run:
        - python >3.11
        - cartopy
        - geopandas <1.1
        - matplotlib
        - pandas >2,<2.3
        - shapely >2,<=2.1
        - xarray <=2025.03.1
        - dask <=2025.3.0
        - netCDF4
        - bottleneck
        - cfgrib
        - rasterio
        - numpy >=2,<3
        - rioxarray <0.19
        - hvplot <0.12
        - bokeh <4
        - panel >=1.6,<1.7
        - datashader
        - geoviews >=1.10
        - geocube
        - ffmpeg
        - fiona
        - gdown <4.6

    test:
      imports:
        - ecodata

    about:
      summary: |
        Tools to access and process remote sensing and other environmental
        data products and prepare them for further use along with animal movement data
      home: https://github.com/jemissik/ecodata
      license: MIT
      license_file: LICENSE
      doc_url: https://ecodata-apps.readthedocs.io
      dev_url: https://github.com/jemissik/ecodata
  
  - name: ecodata-menu
    build:
      noarch: python
      script:
        - mkdir -p "{{ PREFIX }}/Menu"
        - sed "s/__PKG_VERSION__/{{ PKG_VERSION }}/" "{{ RECIPE_DIR }}/menu/conda_menu_config.json" > "{{ PREFIX }}/Menu/ecodata-menu.json"
        - cp "{{ RECIPE_DIR }}/menu/ecodata-icon.png" "{{ PREFIX }}/Menu/ecodata-icon.png"
        - cp "{{ RECIPE_DIR }}/menu/ecodata-icon.icns" "{{ PREFIX }}/Menu/ecodata-icon.icns"
        - cp "{{ RECIPE_DIR }}/menu/ecodata-icon.ico" "{{ PREFIX }}/Menu/ecodata-icon.ico"
        
    requirements:
      build:
        - sed  # [unix]
      host:
        - python >3.11
      run:
        - python >=3.11
        - {{ pin_subpackage('ecodata', exact=True) }}

    test:
      imports:
        - ecodata
    about:
      home: https://github.com/jemissik/ecodata
      license: MIT
      license_file: LICENSE
      doc_url: https://ecodata-apps.readthedocs.io
      dev_url: https://github.com/jemissik/ecodata
      summary: provides menu icons for ecodata
      description: provides menu icons for ecodata

about:
  summary: |
    Tools to access and process remote sensing and other environmental
    data products and prepare them for further use along with animal movement data
  home: https://github.com/jemissik/ecodata
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jemissik
    - madeline-scyphers
